name: scholar_scraper
description: "A Flutter package designed for efficient data scraping from Google Scholar profiles. Extract and analyze publication information, including author names, publication years, and counts. Ideal for building applications related to academic research and citation analysis."
version: 0.0.3

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  firebase_auth: ^4.17.6
  html: ^0.15.4
  http: ^1.2.0
  open_file: ^3.3.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

example:
  path: example

repository: https://github.com/moeen4128/flutter-scholar-scraper.git
